name: Create release pull request

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn lerna bootstrap && yarn lerna build

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
